Multilinguism on interaactionScene
InteraactionGroup/InteraactionScene pull request #38
Opened 2021-05-18 13:55 UTC by PillouMatou

Now you can choose a language in the settings and it will be apply on all the application.

2021-05-21 07:33 UTC, Noars approved these changes
I tried to change the language several times and then refresh the page. No problem, the language we selected is well registered in the database.

2021-05-21 07:38 UTC, Noars approved these changes
I looked everywhere in the site with the language in French then in English and all the text fields are well translated according to the chosen language.

2021-05-21 12:58 UTC, kuhlkrein requested changes
Also all the "hotspot creation" par is not translated (the little dialog that pops when creating an hotspot)

2021-05-21 12:58 UTC, kuhlkrein commented on src/assets/i18n/fr.json
> +    "DwelltimeEnabled": "Activer la temporisation",
replace "temporisation" par "temps de fixation"

2021-05-21 12:58 UTC, kuhlkrein commented on src/assets/i18n/fr.json
> +    "Selectalanguage": "Selectionne un langage",
"une langue" instead of "un langage"

2021-05-21 12:58 UTC, kuhlkrein commented on src/assets/i18n/fr.json
> +    "Remove": "Retirer",
"Supprimer"

2021-05-21 14:22 UTC, kuhlkrein commented
Tests do not pass

2021-07-30 15:02 UTC, kuhlkrein commented
Code works fine but I have an issue with translate:
![image](https://user-images.githubusercontent.com/24478346/127672597-f2bafe24-fa43-466e-bc5e-90684200cd43.png)

2021-08-24 08:44 UTC, merged